
okta:
  oauth:
    issuer: https://dev-135170.oktapreview.com/oauth2/default
    audience: api://default
    clientId: 0oad6zufqgCbXwaxm0h7

spring:
  application:
    name: pokta
  cloud.consul:
    host: localhost
    port: 8500
server:
  port: 8080

#security.ignored: /**
#spring.security.enabled: false
#security.basic.enabled: false
#management.security.enabled: false