spring:
  application:
    name: gateway
  cloud.consul:
    host: localhost
    port: 8500
server:
  port: 8081

#okta:
#  oauth:
#    issuer: https://dev-135170.oktapreview.com/oauth2/default
#    audience: api://default
#    clientId: 0oad6zufqgCbXwaxm0h7

zuul:
  routes:
    echo:
      path: /pokta/**
      serviceId: pokta
      stripPrefix: true
      sensitiveHeaders: